regsvr32 BGraphe_OCX.ocx -s
regsvr32 ExtendedVScrollbar_OCX.ocx -s
regsvr32 FileView_OCX.ocx -s
regsvr32 ProgressBar_OCX.ocx -s
regsvr32 HexViewer_OCX.ocx -s
regsvr32 LanguageTranslator.ocx -s
regsvr32 Disassembler_DLL.dll -s
regsvr32 ProcessView_OCX.ocx -s
regsvr32 DriveView_OCX.ocx -s