regsvr32 BGraphe_OCX.ocx -s -u
regsvr32 ExtendedVScrollbar_OCX.ocx -s -u
regsvr32 FileView_OCX.ocx -s -u
regsvr32 ProgressBar_OCX.ocx -s -u
regsvr32 HexViewer_OCX.ocx -s -u
regsvr32 Disassembler_DLL.dll -s -u
regsvr32 ProcessView_OCX.ocx -s -u
regsvr32 DriveView_OCX.ocx -s -u
regsvr32 FileSystemLibrary.dll -s -u